name: Deploy to Mini PC

on:
  push:
    branches:
      - main # Jalankan aksi ini ketika ada push ke branch main

jobs:
  deploy:
    runs-on: self-hosted # Menggunakan self-hosted runner di server Mini PC lu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env file (Optional)
        # Langkah ini opsional. Buat secret dengan nama VITE_APP_ENV di GitHub (Settings > Secrets and variables > Actions).
        run: |
          echo "${{ secrets.VITE_APP_ENV }}" > .env
          echo "File .env telah berhasil dibuat dari GitHub Secrets."

      - name: Build and Deploy with Docker Compose
        # Matikan container lama dulu biar nggak bentrok port, baru bangun dan jalankan yang baru
        run: |
          docker compose down
          docker compose up --build -d

      - name: Clean up old Docker Images
        # Menghapus image yang menggantung agar SSD Mini PC lu nggak penuh
        run: |
          docker image prune -f